### PR TITLE
Fix DatePickerDialog onSaveInstanceState

### PR DESCRIPTION
**Pull request by rlac**

### CODE REVIEW

**Comment by drawers** [comment]
Thanks - have you tested this? I mean by turning on "Don't keep activities" in System/Developer options and then closing/reopening while the dialog is open?

**Comment by rlac** [comment]
Yes, I've tested this with a DialogFragment managing a DatePickerDialog, using both Don't Keep Activities and killing the app process while it's in the background then restoring.

**Comment by drawers** [comment]
Thanks very much - I really appreciate this. I will definitely make a release from this soon - just give me some time !

**Comment by drawers** [comment]
Thanks again - you can now use version `1.0.5` which incorporates your fix.

**Pull request merged**
