### PR TITLE
add custom dialog title functionality

### PR DESCRIPTION
**Pull request by magnox**

### CODE REVIEW

**Comment by drawers** [comment]
Nice! sorry about the delay, would you mind updating the version number of the project? Then I can merge ;-)

**Comment by magnox** [comment]
Done! :)

**Comment by magnox** [comment]
Do I have to push a tag as well or is that something you have to do in order to create a new release? @drawers

**Comment by drawers** [comment]
Hmm seems will need to tag

**Comment by magnox** [comment]
I don't seem to have permission to tag...

**Comment by magnox** [comment]
I didn't quite get your last response. Will you be adding the tag?

**Comment by drawers** [comment]
Sorry for the delay, I added the tag. Thanks for the pull request. Please let me know if there are any more problems

**Pull request merged**
