### PR TITLE
Hold title improvements

### PR DESCRIPTION
**Pull request by sasfmlzr**
I created two fields - isTitleHold and titleText. But rotate screen not worked for this library. This library not used onSavedInstanceState and onRestore. Ui tests successfully completed.

### CODE REVIEW

**Comment by sasfmlzr** [comment]
For testing:

@VisibleForTesting
    void showDate(int year, int monthOfYear, int dayOfMonth, int spinnerTheme) {
        dialog = new SpinnerDatePickerDialogBuilder()
                .context(MainActivity.this)
                .callback(MainActivity.this)
                .setTitleText("Amazfffing")
                .spinnerTheme(spinnerTheme)
                .defaultDate(year, monthOfYear, dayOfMonth)
                .build();

        dialog.show();
    }

**Comment by sasfmlzr** [comment]
This is the wrong architecture. You should delete AlertDialog and leave only DatePicker. Why? If i want to add new View to the AlertDialog(for example TextView, EditView...), i can't do it. Maybe i want to add few DatePicker in one AlertDialog, but i can't)

**Comment by drawers** [comment]
Hi! Thanks so much for the pull request 👍  What do you mean by `isTitleHold`? Does it mean to have just one title that doesn't change?

**Comment by sasfmlzr** [comment]
Yes of course. Title doesn't change, when we changed date.

**Comment by drawers** [comment]
I will have to find another way to address the issues you mentioned

**Pull request closed without merging**
