### PR TITLE
Make spinner working for android 16

### PR DESCRIPTION
**Pull request by kmenager**

### CODE REVIEW

**Comment by kmenager** [comment]
Hello @drawers.
Is it possible for you to create a new release based on this pull request ?

**Comment by drawers** [comment]
Hi, thanks very much for the pull request. I have been looking at pre-18 support myself.

However, just changing the API level is not enough to make the library work with SDK < 18. The reason is because we are calling `DateFormat#getBestDateTimePattern` which is only available on SDK 18+. Also, there are some issues with how the spinner displays on < 18 - you can't seem to style the NumberPicker divider easily. Ideally we would want some consistent solution

Can we leave the pull request open for now? If we can get a tentative solution it is possible to reference a SNAPSHOT release from a commit in your project

**Comment by drawers** [comment]
Also, the Google Play Services are so that people can import their project into Firebase and run the cloud tests. I'm sorry if it's a bit confusing. Perhaps there is a solution where we make that clearer in the Gradle script?

**Review by basavaraj191991 — APPROVED** [review]

**Comment by drawers** [comment]
This pull request has been superseded by #14

**Pull request closed without merging**
